### ISSUE TITLE
Google Gemini Support

### ISSUE THREAD

**Issue by gunpal5** [tryAGI/LangChain#89]
## What would you like to be added:
Support for Recently launched Google Gemini
https://ai.google.dev/

## Why is this needed:
Gemini is the latest AI Model from Google. It is a direct competitor of OpenAI's GPT

**Comment by HavenDV** [comment]
I think we need to use https://www.nuget.org/packages/Google.Apis.Aiplatform.v1beta1 when we start implementing this

**Comment by gunpal5** [comment]
@HavenDV Google Gemini doesn't have any C# SDK yet, we need to use their REST APIs. I have started working on it. I should have it completed within 2-3 days.

**Comment by HavenDV** [comment]
I'm inclined to believe that it exists, it's just not documented.
You need to take a closer look at this, there are recent changes here:
https://github.com/googleapis/google-api-dotnet-client/tree/main/Src/Generated
https://raw.githubusercontent.com/googleapis/google-api-dotnet-client/main/Src/Generated/Google.Apis.Aiplatform.v1beta1/Google.Apis.Aiplatform.v1beta1.cs

Even if it turns out that this is not the case, you can also first check if there is an openapi/swagger specification here, and use that for automatic generation using NSwag/Kiota
